replicas: 1
namespace: ns-26

app:
  name: "server"
  path: "geexmo/docker-images"
  version: "server1"

resources:
  requests:
    memory: "200M"
    cpu: "1"
  limits:
    memory: "200M"
    cpu: "1"

service:
  enabled: true
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000

env:
    DB_NAME: "postgres"
    DB_USER: "postgres"
    DB_PASSWORD: "password"
    DB_HOST: "localhost"
    DB_PORT: "5432"
